apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-todo-get-task-api
spec:
  type: {{ .Values.gettask.type }}
  selector:
    app: {{ .Release.Name }}-todo-get-task-api
  ports:
    - port: {{ .Values.gettask.ports.port }}
      targetPort: {{ .Values.gettask.ports.targetPort }}
      
