apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-todo-delete-tasks-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-todo-delete-tasks-api
  template:
    metadata:
      name: {{ .Release.Name }}-todo-delete-tasks
      labels:
        app: {{ .Release.Name }}-todo-delete-tasks-api
    spec:
      containers:
       - name: {{ .Release.Name }}-todo-delete-tasks-api
         image: {{ .Values.deletetask.image.acr_name }}/{{ .Values.deletetask.image.name }}:{{ .Values.deletetask.image.tag }}
         ports:
          - containerPort: {{ .Values.deletetask.ports.containerPort }}
         env: 
           - name: {{ .Values.deletetask.env.name }}
             value: {{ .Values.deletetask.env.value }}
