apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-todo-delete-tasks-api-ingress
spec:
  ingressClassName: {{ .Values.deletetask.ingressClassName }}
  rules:
    - host: {{ .Values.deletetask.rules.host }}
      http:
        paths:
          - pathType: {{ .Values.deletetask.paths.pathType }}
            path: {{ .Values.deletetask.paths.path }}
            backend:
              service:
                name: {{ .Release.Name }}-todo-delete-tasks-api
                port:
                  number: {{ .Values.deletetask.port.number }}
                  
