apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-todo-delete-tasks-api
spec:
  type: {{ .Values.deletetask.type }}
  selector:
    app: {{ .Release.Name }}-todo-delete-tasks-api
  ports:
    - port: {{ .Values.deletetask.ports.port }}
      targetPort: {{ .Values.deletetask.ports.containerPort }}
      
